apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | default "kfops" }}
  name: argo-pipeline-runner-sa
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}        
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-pipeline-runner-clusterrole
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}        
rules:
- apiGroups:
  - serving.kserve.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - '*'
  verbs:
  - '*'  
---
# Both AuthorizationPolicy below are related to issue: https://github.com/kubeflow/kfserving/issues/1558  
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allowlist-by-paths
  namespace: istio-system
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}        
spec:
  selector:
    matchLabels:
      component: predictor
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /metrics
        - /healthz
        - /ready
        - /wait-for-drain
        - /v1/models/*
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allowlist-by-paths-transformer
  namespace: istio-system
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}        
spec:
  selector:
    matchLabels:
      component: transformer
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /metrics
        - /healthz
        - /ready
        - /wait-for-drain
        - /v1/models/*
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-pipeline-runner-clusterrolebinding
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-pipeline-runner-clusterrole
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | default "kfops" }}
  name: argo-pipeline-runner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-pipeline-runner
  namespace: {{ .Release.Namespace | default "kfops"  }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}      
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - kubeflow.org
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-pipeline-runner-rolebinding
  namespace: {{ .Release.Namespace | default "kfops" }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-pipeline-runner
subjects:
- kind: ServiceAccount
  name: argo-pipeline-runner-sa
  namespace: {{ .Release.Namespace | default "kfops"  }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-pipeline-runner-access-kubeflow-namespace
  namespace: kubeflow
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}      
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-pipeline-runner-rolebinding-kubeflow-namespace
  namespace: kubeflow
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "additionalLabels" . | nindent 4 }}
  {{- include "annotations" . | nindent 2 }}      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-pipeline-runner-access-kubeflow-namespace
subjects:
- kind: ServiceAccount
  name: argo-pipeline-runner-sa
  namespace: {{ .Release.Namespace | default "kfops"  }}